# Generated by Django 3.1.6 on 2021-06-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Washing_Machine', models.CharField(max_length=800)),
                ('Dryer', models.CharField(max_length=800)),
                ('Washing_Machine_With_Dryer', models.CharField(max_length=800)),
                ('Automatic_Washing_Machine', models.CharField(max_length=800)),
                ('Extension', models.CharField(max_length=800)),
                ('Char', models.CharField(choices=[('Washing Machine', 'washing machine'), ('Dryer', 'dryer'), ('Washing Machine With Dryer', 'washing machine with dryer'), ('Extension', 'extension'), ('Automatic Washing Machine', 'automatic washing machine')], max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dailyplan.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=800, null=True)),
                ('Address', models.TextField(max_length=800, null=True)),
                ('Contact_Number', models.TextField(max_length=800, null=True)),
                ('Email', models.TextField(max_length=800, null=True)),
                ('Contact_Person', models.TextField(max_length=800, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('kamote', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyplan.user')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Del', models.CharField(max_length=800, null=True)),
                ('For_Deliver', models.CharField(max_length=800, null=True)),
                ('For_Pickup', models.CharField(max_length=800, null=True)),
                ('Dels', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyplan.user')),
            ],
        ),
    ]
